### ISSUE TITLE
thanks for making the new toolchain available!!

### ISSUE THREAD

**Issue by jwijffels** [r-windows/docs#1]
I'm trying out the new toolchain on R 3.5.2. Works great. Only thing that I had to do was set
`C:/rtools40/mingw64/bin/` in the `BINPREF` environment variable to make this work without using the r-testing.
Works great! Really thanks for making this package manager available as well as to have all the rtools-packages. Makes my day!

**Comment by jeroen** [comment]
Oh be careful because R 3.5.2 and the binary packages have been compiled with the old toolchain, so you could get unexpected crashes when you mix this with packages compiled with the new toolchain.

**Comment by jwijffels** [comment]
Ah. Good to know.

**Comment by jeroen** [comment]
If you want to use the new toolchain I highly recommend installing the special R-testing build: https://cran.r-project.org/bin/windows/testing/rtools40.html

**Comment by jwijffels** [comment]
Will do.
