### ISSUE TITLE
Linux commands in documentation for Rtools40 on Windows

### ISSUE THREAD

**Issue by vincentvanhees** [r-windows/docs#11]
I develop an [R package](https://github.com/wadpac/GGIR) in Linux and would like to test it on a Windows machine, which led me to your instructions for Rtools.

In the docs for Rtools40 on Windows: https://cran.rstudio.com/bin/windows/Rtools/ I see `PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"` and `writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")`

These seem Linux commands to me and I am not sure what to do with them in a Windows environment... or am I misunderstanding something?

Thanks for all your efforts to maintain this repository.

**Comment by vincentvanhees** [comment]
... I mean the file paths are Linux specific. Some guidance on retrieving the file path in Windows would be valuable.

**Comment by jeroen** [comment]
Why do you think those are Linux commands? This entire manual is only for Windows. These are Windows paths, as you can recognize from the back slashes. 

The `RTOOLS40_HOME` variable is set by the Windows installer for rtools.

Just try it, it will work.

**Comment by vincentvanhees** [comment]
Sorry, I assumed things too quickly.

After installing Rtools I get:

```
> PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"
Error: '\u' used without hex digits in character string starting ""${RTOOLS40_HOME}\u"
```
even after restarting RStudio

**sessionInfo:**
```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.0.0 tools_4.0.0  
```

**Comment by vincentvanhees** [comment]
If I replace \ by \\ it works :)

**Comment by vincentvanhees** [comment]
Conclusion:
` PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"`

should be

` PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"`

Do you want me to make a pull request?

**Comment by jeroen** [comment]
I'm pretty sure it is correct as stated right now. You only need to escape the backslash within the R code, but not in the `~/.Renviron` file itself.

**Comment by vincentvanhees** [comment]
Thanks, If I am the only person who encountered this then I guess it is just something on my site that caused it. At least the error message (copy below) was real for me.

```
> PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"
Error: '\u' used without hex digits in character string starting ""${RTOOLS40_HOME}\u"
```
and it disappeared after I added the double backward slash. Feel free to close this issue.

**Comment by vincentvanhees** [comment]
Sorry, my mistake I was using PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}" in the R console command line and did not add it to the `~/.Renviron` file.
