### ISSUE TITLE
Need help with an updated path

### ISSUE THREAD

**Issue by Minou27** [r-windows/docs#13]
I'm pretty new and I installed my RTools in a different location based on how I have my R/RStudio set up.  How do I write the new path?  

Here's the location that I have it installed in:

C:\\Users\\Melody\\DOCUME~1\\R\\WIN-LI~1\\3.4\\rtools40\\usr\\bin\\make.exe"

TIA!

**Comment by jeroen** [comment]
Which version of R and rtools did you install?

**Comment by Minou27** [comment]
I thought I had updated R but it looks like I didn't.  I did now and it seems to be working ok.  Should I still update the path?

**Comment by jeroen** [comment]
Just follow instructions in https://cran.r-project.org/bin/windows/Rtools/ :)
