### ISSUE TITLE
Bug during compilation

### ISSUE THREAD

**Issue by rbotafogo** [r-windows/docs#20]
I'm getting the following bug after installing rtools4:

symbol not definedbin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export R_init_backports
symbol not definedbin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export dotsElt
: symbol not definedbin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export dotsLength
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'backports'

Googled it but couldn't find anything

**Comment by jeroen** [comment]
Please include what you did to arrive at this error.

**Comment by rbotafogo** [comment]
I installed rtools4 and tried:

install.packages("jsonlite", type = "source")

Installation did not work with the above errors

**Comment by rbotafogo** [comment]
I found the error... my PATH wasn't correct.  Thanks
