### ISSUE TITLE
How do I report a bug in the Rtools 4.0 Windows setup?

### ISSUE THREAD

**Issue by marcoxa** [r-windows/docs#23]
Hi

this came up while installing an update for "ps" in the lastest R/Rtools/Rstudio combination.  I am posting here because I was not able to find a place where to send the bug report (hint: add a pointer in the documentation). 

I was then able to reproduce it on a simpler case.  Bottom line: while the C compiler package quoting issue was fixed, the loader (ld.exe) was not.

```
g:\My Drive\Work\Projects\Hacking\elisp\iron-main\tests>"c:\Program Files\R\Rtools40\mingw64\bin\gfortran" hello.f 
"c:\Program Files\R\Rtools40\mingw64\bin\gfortran" hello.f 
c:/Program Files/R/Rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find c:/Program: No such file or directory
c:/Program Files/R/Rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find Files/R/Rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/lib/../lib/default-manifest.o: No such file or directory
collect2.exe: error: ld returned 1 exit status

```

Any idea about how to fix this?

All the best

Marco Antoniotti

**Comment by jeroen** [comment]
The best solution is to install rtools in a path without spaces. Preferably the default `c:\\rtools40`. I'll see if we can improve the quoting situation.

**Comment by jeroen** [comment]
OK there is nothing I can do about this because the path to LD is determined by gcc itself, it is out of our control. To fix this you need to open an bug report in https://github.com/msys2/MINGW-packages

**Comment by marcoxa** [comment]
Thank you for your reply.  Obviously it is a bug in msys2/MINGW-packages.  Even in gcc.

As for the suggestion of installing Rtools in a non standard path, ok, I got that far.  It is still a bug, given the current environment.

All the best

Marco Antoniotti
