### ISSUE TITLE
Unable to install base-devel

### ISSUE THREAD

**Issue by mtvincen** [r-windows/docs#27]
I am attempting to install hunspell (https://github.com/hunspell/hunspell) onto my computer using an rtools40 version of Msys. I am using a windows 10 computer but do not have admin authorization. I am attempting to install base-devel but I keep getting an "error: target not found: base-devel " I have run the command I am attempting to install with the debug option below to try to help with resolving the issue. I have run pacman -Syu and pacman -Su to make sure everything is up to date and am still getting the same error.

 pacman -S base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool --debug
debug: pacman v5.2.1 - libalpm v12.0.1
debug: config: attempting to read file /etc/pacman.conf
debug: config: new section 'options'
debug: config: HoldPkg: pacman
debug: config: HoldPkg: curl
debug: config: HoldPkg: gnupg
debug: config: arch: x86_64
debug: config: SigLevel: Required
debug: config: SigLevel: DatabaseOptional
debug: config: LocalFileSigLevel: Optional
debug: config: new section 'mingw32'
debug: config file /etc/pacman.conf, line 72: including /etc/pacman.d/mirrorlist.mingw32
debug: config: SigLevel: Never
debug: config: new section 'mingw64'
debug: config file /etc/pacman.conf, line 75: including /etc/pacman.d/mirrorlist.mingw64
debug: config: SigLevel: Never
debug: config: finished parsing /etc/pacman.conf
debug: setup_libalpm called
debug: option 'logfile' = /var/log/pacman.log
debug: option 'gpgdir' = /etc/pacman.d/gnupg/
debug: option 'hookdir' = /etc/pacman.d/hooks/
debug: option 'cachedir' = /var/cache/pacman/pkg/
debug: registering sync database 'mingw32'
debug: database path for tree mingw32 set to /var/lib/pacman/sync/mingw32.db
debug: setting usage of 15 for mingw32 repository
debug: adding new server URL to database 'mingw32': https://cloud.r-project.org/bin/windows/Rtools/4.0/mingw32
debug: adding new server URL to database 'mingw32': https://cran.r-project.org/bin/windows/Rtools/4.0/mingw32
debug: adding new server URL to database 'mingw32': https://dl.bintray.com/rtools/mingw32
debug: registering sync database 'mingw64'
debug: database path for tree mingw64 set to /var/lib/pacman/sync/mingw64.db
debug: setting usage of 15 for mingw64 repository
debug: adding new server URL to database 'mingw64': https://cloud.r-project.org/bin/windows/Rtools/4.0/mingw64
debug: adding new server URL to database 'mingw64': https://cran.r-project.org/bin/windows/Rtools/4.0/mingw64
debug: adding new server URL to database 'mingw64': https://dl.bintray.com/rtools/mingw64
debug: loading package cache for repository 'mingw32'
debug: opening archive /var/lib/pacman/sync/mingw32.db
debug: added 156 packages to package cache for db 'mingw32'
debug: loading package cache for repository 'mingw64'
debug: opening archive /var/lib/pacman/sync/mingw64.db
debug: added 156 packages to package cache for db 'mingw64'
debug: loading group cache for repository 'mingw32'
debug: loading group cache for repository 'mingw64'
error: target not found: base-devel
debug: adding package 'mingw-w64-x86_64-libtool'
debug: loading package cache for repository 'local'
debug: added 108 packages to package cache for db 'local'
warning: mingw-w64-x86_64-libtool-2.4.6-11 is up to date -- reinstalling
debug: adding package mingw-w64-x86_64-libtool-2.4.6-11 to the transaction add list
debug: unregistering database 'local'
debug: freeing package cache for repository 'local'
debug: unregistering database 'mingw32'
debug: freeing package cache for repository 'mingw32'
debug: freeing group cache for repository 'mingw32'
debug: unregistering database 'mingw64'
debug: freeing package cache for repository 'mingw64'
debug: freeing group cache for repository 'mingw64'

**Comment by jeroen** [comment]
Why are you trying to install hunspell? No R package needs this (the R package called hunspell contains the libhunspell code)?

To install base-devel you need to uncomment the msys2 repo in `/etc/pacman.conf`

**Comment by mtvincen** [comment]
I was just trying to use the MSYS in Rtools to compile the program to be used in emacs wihtout needing to install a separate version of MSYS (not specifically Rtools related I guess). I will try uncommenting this. thanks
