### ISSUE TITLE
R Tools Silent install

### ISSUE THREAD

**Issue by itsjimbo** [r-windows/docs#32]
Are there any silent install options?

I tried following along with https://silentinstallhq.com/msys2-silent-install-how-to-guide/ 
something like
```
rtools40v2-x86_64.exe  --platform minimal --script silent-install.js InstallDir=C:\test_r_tools\
```
but variables do not change, and I cannot get silent mode to work without modal windows popping up prompting for path.

**Comment by jeroen** [comment]
Our installer uses innosetup so you can use `/VERYSILENT /SUPPRESSMSGBOXES`, see for [here](https://github.com/r-windows/r-base/blob/master/scripts.ps1#L38-L44) for a powershell example, or [here](https://github.com/r-lib/actions/blob/20307d099c364c4a5107b681d37e49e62c790fb8/setup-r/src/installer.ts#L349-L418) for a third party example in github actions.
