### ISSUE TITLE
pacman workaround.

### ISSUE THREAD

**Issue by Phylloxera** [r-windows/docs#35]
Was attempting to install package XML from source using your workaround (R 4.1.2; R Studio 1.4.1717) Guessing from structure that `pacman -S mingw-w64-{i686,x86_64}-libxml2` is not an R command (it also doesn't work). Was thinking it could be a powershell command, but that also didn't work. I guess I either need clarification on the pacman command or I need to back up to another root problem, or both... thoughts?

- R error: ' Error: unexpected symbol in "pacman -S mingw" ' 
- Powershell error: ' At line:1 char:26 + pacman -S mingw-w64-{i686,x86_64}-libxml2 + ~ Missing argument in parameter list. + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException + FullyQualifiedErrorId : MissingArgument '

**Comment by jeroen** [comment]
You run it in the rtools40 shell, see: https://github.com/r-windows/docs/blob/master/rtools40.md#readme
