### ISSUE TITLE
RStudio (R 4.2.1) does not locate gcc (gcc.exe) at C:\rtools42\mingw64\bin

### ISSUE THREAD

**Issue by mmarikar** [r-windows/docs#37]
Instead of finding gcc at C:\rtools42\mingw64\bin it finds it at /x86_64-w64-mingw32.static.posix/bin/gcc.exe
Thus older gcc compiler based C programs are breaking.
Can you please provide a fix.
Thanks,
Mo Marikar
EPA

**Comment by jeroen** [comment]
The new rtools42 is maintained by r-core, you have to ask this on the r-devel mailing list or https://bugs.r-project.org/enter_bug.cgi

**Comment by mmarikar** [comment]
Can you please provide r-devel mailing list and even better would be the email for the person(s) handling this.
The Govt Agency where I work does not allow access to Bugzilla as there is a security issue with that site.
Thanks,
Mo Marikar

**Comment by jeroen** [comment]
The email is tomas.kalibera@gmail.com

**Comment by mmarikar** [comment]
Jeroen,
Can you please provide the r-devel mailing list since the EPA where I work
does not allow access to bugzilla
Thanks,
Mo Marikar
