### ISSUE TITLE
Document that rtools40 should be on path

### ISSUE THREAD

**Issue by andrie** [r-windows/docs#7]
If the correct version of `make` is not on the path, package compilation can lead to errors like this:

```
ERROR: compilation failed for package '....'
* removing 'C:/R/R-devel/library/....'
```

This is because the correct version of rtools is not on the path.  To fix this, you should add the following line to your `.Renviron` file:

```r
PATH = "${RTOOLS40_HOME}\usr\bin;${PATH}"
```

**Comment by jeroen** [comment]
Fixed in the readme: https://github.com/r-windows/docs
